routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware'=>['auth']],function(){
    Route::get('/','DashboardController@dashboard')->name('admin.index');
    Route::get('/employee/serach', 'EmployeeController@search')->name('admin.search');
    Route::get('/start/data-chart','StartController@chartData');
    Route::get('/start/socket-chart','StartController@newEvent');
    Route::get('/start/send-message','StartController@sendMessage');
    Route::resource('/employee','EmployeeController',['as'=>'admin']);

});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Emoloyee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Emoloyee extends Model
{
    //
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Employee extends Model
{
    protected  $fillable = ['name','img','position','time_of_hiring','slug','salary','boss_id','published','created_by','modified_by'];

    public function setSlugAttribute($value){
        $this->attributes['slug']= Str::slug(mb_substr($this->name,0, 40). "-" .\Carbon\Carbon::now()->format('dmyHi'));
    }

    public function children(){
        return $this->hasMany(self::class,'boss_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    //Dashboard
    public function dashboard(){
        return view('admin.dashboard');
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Employee;
use App\User;
use DeepCopy\f004\UnclonableItem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use File;
use Illuminate\Support\Facades\Storage;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        return view('admin.employees.index',
            ['employees'=> Employee::paginate(10),
                'users'=>User::all()
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      
        return view('admin.employees.create',[
            'employee'=>Employee::all(),
            'employees'=> Employee::with('children')->where('boss_id','0')->get(),
            'delimiter'=>'-'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $img ="";
        if($request->hasFile('img')){
         $destinationPath = 'photo';
         $file =$request->img;
          $extension=$file->getClientOriginalExtension();
          $fileName =rand(1111,9999).".".$extension;
            $file->move($destinationPath,$fileName);
            $img =$fileName;
        }


        
        Employee::create($request->all());




        return redirect()->route('admin.employee.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);
        $boss = Employee::find($employee->boss_id);


      return view('admin.employees.show',compact(['employee','boss']));
    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('admin.employees.edit',[
            'employee'=>$employee,
            'employees'=> Employee::with('children')->where('boss_id','0')->get(),
            'delimiter'=>''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $employee->update($request->except('slug'));

        return redirect()->route('admin.employee.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {

        $employee->delete();
        return redirect()->route('admin.employee.index');
    }

    public function search(Request $request){
$x=5;
        request()->get('search');
       $name = DB::table('employees')
            ->where(function ($query)  {

                $query->where("name", "like", "%" . request("search") . "%")
                    ->orWhere("position", "like", "%" . request("search") . "%")
                    ->orWhere("salary", "like", "%" . (int)request("search") . "%");


            })
            ->get();
dump($name);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/StartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class StartController extends Controller
{
    public  function chartData()
    {
        return[
            'labels'=>['mart','april','may','jun'],
            'datasets'=>array([
                'label'=>'Sale',
                'BackgroundColor'=>'F26202',
                'data'=>[15000,5000,10000,30000],
            ])

        ];
    }

    public  function newEvent(\illuminate\Http\Request $request){
        $request =[
            'labels'=>['mart','april','may','jun'],
            'datasets'=>array([
                'label'=>'Sale',
                'BackgroundColor'=>'F26202',
                'data'=>[15000,5000,10000,30000],
        ])
            ];
        if($request->has('label')){
            $request['label'][] =$request->input('label');
            $request['datasets'][0]['data'][]=(integer)$request->input('sale');

            if($request->has('realtime')){
                if(filter_var($request->input('realtime'),FILTER_VALIDATE_BOOLEAN)){
                    event(new\App\Events\NewEvent($result));
                }
            }
        }
    }

    public  function sendMessage(\illuminate\Http\Request $request){
        event(App\Events\NeWMessage($request->input('message')));
    }
}

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app');

@section('content')
    <h1>Admin test</h1>
    @endsection

resources/views/admin/employees/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">

        <form class="form-horizontal" action="{{route('admin.employee.store')}}" method="post"  enctype="multipart/form-data">
            {{ csrf_field() }}
            {{-- Form include --}}
            @include('admin.employees.partials.form')
        </form>
    </div>
@endsection

resources/views/admin/employees/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">

        <form class="form-horizontal" action="{{route('admin.employee.update',$employee)}}" method="post">
            <input type="hidden" name="_method", value="put">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.employees.partials.form')
        </form>
    </div>
@endsection

resources/views/admin/employees/index.blade.php
@extends('admin.layouts.app')

@section('content')
            <div class="col-lg-8">
            <a href="{{route('admin.employee.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o">Add worker</i></a>
            <table class="table table-striped">
                <thead>
                <th>name</th>
                <th>position</th>
                <th>time of hiring</th>
                <th>salary</th>
                <th>ection</th>
                </thead>
                <tbody>
                @forelse($employees as $employee)
                    <tr>
                        <td>{{$employee->name}}</td>
                        <td>{{$employee->position}}</td>
                        <td>{{$employee->time_of_hiring}}</td>
                        <td>{{$employee->boss_name}}</td>
                        <td>{{$employee->salary}}</td>
                        <td>
                            <form onsubmit="if(confirm('Delete?')){return true}else{return false}" action="{{route('admin.employee.destroy',$employee)}}" method="post">
                                {{--<input type="hidden" name="_method" value="DELETE">--}}


                                <a class="btn btn-info" href="{{route('admin.employee.show',$employee)}}">show</a>
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                                <a href="{{route('admin.employee.edit',$employee)}}"><i class="fa fa-edit"></i></a>
                                <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                            </form>

                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="3" class="text-center"><h2> data is aption</h2></td>
                    </tr>
                    @endforelse
                </tbody>
                <tfoot>
                    <td colspan="3">

                    </td>
                </tfoot>
            </table>
                <chartline-component></chartline-component>
                <socket-chat-component></socket-chat-component>
                {{--<socket-component></socket-component>--}}
            </div>

            <aside-component :urldata="{{json_encode($users)}}"></aside-component>
            <ajax-component></ajax-component>
@endsection

resources/views/admin/employees/partials/employees.blade.php
@foreach ($employees as $employee_list)

<option value="{{$employee_list->id or ""}}"

    @isset($employee->id)

    @if($employee->boss_id == $employee_list->id)
            @selected=""

        @endif
    @if($employee->id ==$employee_list->id)
        hidden=""
    @endif
    @endisset
>

{!! $delimiter or "" !!}{{$employee_list->name or ""}}
</option>
@include('admin.employees.partials.employees',[
'employees'=>$employee_list->children,
'delimeter'=> ' - ' . $delimiter])


@endforeach

resources/views/admin/employees/partials/form.blade.php
<label for="">Статус</label>
<select class="form-control" name="published">
    @if (isset($employee->id))
        <option value="0" @if ($employee->published == 0) selected="" @endif>Не опубликовано</option>
        <option value="1" @if ($employee->published == 1) selected="" @endif>Опубликовано</option>
    @else
        <option value="0">Не опубликовано</option>
        <option value="1">Опубликовано</option>
    @endif
</select>

<label for="">nmae of worker</label>
<input type="text" class="form-control" name="name" placeholder="name 0f worker" value="{{$employee->name or ""}}" required>

<label for="">photo</label>
<img src="'/photo/'.$employee->img}}" alt="">
<input type="file" class="form-control" name="img" placeholder="name 0f worker" value="{{$employee->img or ""}}" required>

<label for="">position of worker</label>
<input type="text" class="form-control" name="position" placeholder="postion 0f worker" value="{{$employee->position or ""}}" required>

<label for="">time_of_hiring</label>
<input type="text" class="form-control" name="time_of_hiring" placeholder="time_of_hiring" value="{{$employee->time_of_hiring or ""}}" required>

<label for="">Slug</label>
<input class="form-control" type="text" name="slug" placeholder="Автоматическая генерация" value="{{$employee->slug or ""}}" readonly="">

<label for="">salary</label>
<input type="text" class="form-control" name="salary" placeholder="salary" value="{{$employee->salary or ""}}" required>


<label for="">Boss</label>
<select class="form-control" name="boss_id">
    <option value="0">-- without boss --</option>
    @include('admin.employees.partials.employees', ['employees' => $employees])
</select>
<hr />

<label for="">created by</label>
<input type="text" class="form-control" name="created_by" placeholder="created_by" value="{{$employee->created_by or ""}}" required>

<label for="">modifidet by</label>
<input type="text" class="form-control" name="modifietd_by" placeholder="modifietd_by" value="{{$employee->modifietd_by or ""}}" required>




<input class="btn btn-primary " type="submit" value="Save">

resources/views/admin/employees/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <a class="btn btn-info pull-right" href="{{route('admin.employee.index')}}">Back to list</a>
            <h1>{{$employee->name}}</h1>
                <img class="imng-fluid" src="{{asset('photo/'.$employee->img)}}" alt="">
            @if($boss)
            <h2>{{$boss->name}}</h2>
            @endif
            </div>
    </div>
@endsection

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .search-form .form-group {
            float: right !important;
            transition: all 0.35s, border-radius 0s;
            width: 32px;
            height: 32px;
            background-color: #fff;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
            border-radius: 25px;
            border: 1px solid #ccc;
        }
        .search-form .form-group input.form-control {
            padding-right: 20px;
            border: 0 none;
            background: transparent;
            box-shadow: none;
            display:block;
        }
        .search-form .form-group input.form-control::-webkit-input-placeholder {
            display: none;
        }
        .search-form .form-group input.form-control:-moz-placeholder {
            /* Firefox 18- */
            display: none;
        }
        .search-form .form-group input.form-control::-moz-placeholder {
            /* Firefox 19+ */
            display: none;
        }
        .search-form .form-group input.form-control:-ms-input-placeholder {
            display: none;
        }
        .search-form .form-group:hover,
        .search-form .form-group.hover {
            width: 100%;
            border-radius: 4px 25px 25px 4px;
        }
        .search-form .form-group span.form-control-feedback {
            position: absolute;
            top: -1px;
            right: -2px;
            z-index: 2;
            display: block;
            width: 34px;
            height: 34px;
            line-height: 34px;
            text-align: center;
            color: #3596e0;
            left: initial;
            font-size: 14px;
        }
    </style>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">crm</a>
                        <ul class="drodown" role="menu">
                            <li><a href="{{route('admin.employee.index')}}">Employees</a></li>
                        </ul>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @guest
                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                        @endguest
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
<search></search>

    @yield('content')
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>